version: 2.0

defaults: &defaults
  working_directory: ~/release-probe
  docker:
      - image: ychescale9/android-sdk:1.0
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx2g"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false"
    TERM: dumb

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew clean assemble bundle
      - store_artifacts:
          path: app/build/outputs/

      - run:
          name: Test
          command: |
            ./gradlew test
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp --parents {} ~/junit/ \;
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - run:
          name: Android Lint
          command: ./gradlew :app:lint
      - store_artifacts:
          path: app/build/reports/lint-results.html

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
