version: 2.0

# Docker configs
android_config: &android_config
  working_directory: ~/release-probe
  docker:
      - image: ychescale9/android-sdk:1.0
  environment:
    _JAVA_OPTIONS: "-Xmx2g -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2g" -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false'
    TERM: dumb

# Cache
save_gradle_cache: &save_gradle_cache
  save_cache:
    key: $CACHE_VERSION-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    paths:
      - ~/.gradle

restore_gradle_cache: &restore_gradle_cache
  restore_cache:
    key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

# Workspace
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/release-probe

persist_android_workspace: &persist_android_workspace
  persist_to_workspace:
    root: ~/release-probe
    paths:
      - app/build/outputs/apk/
      - app/build/outputs/bundle/
      - app/build/outputs/mapping/

# Branching filters
master_only: &master_only
  filters:
    branches:
      only: master

jobs:
  build:
    <<: *android_config
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo "Cache version: $CACHE_VERSION"
            echo 'export BUILD_NUMBER="$CIRCLE_BUILD_NUM"' >> $BASH_ENV
      - checkout
      - *restore_gradle_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - *save_gradle_cache
      - run:
          name: Decrypt Secrets
          command: |
            openssl aes-256-cbc -md sha256 -d -in secrets/release-probe.aes -out secrets/release-probe.keystore -k $ENCRYPT_KEY
      - run:
          name: Assemble
          command: |
            ./gradlew assemble bundleProdRelease
      - store_artifacts:
          path: app/build/outputs/
      - run:
          name: Cleanup Secrets
          command: rm -f secrets/release-probe.keystore
      - *persist_android_workspace

  unit_tests:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - *save_gradle_cache
      - run:
          name: Test
          command: |
            ./gradlew test
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp --parents {} ~/junit/ \;
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  static_analysis:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - *save_gradle_cache
      - run:
          name: Android Lint
          command: ./gradlew :app:lint
      - store_artifacts:
          path: app/build/reports/lint-results.html
      - run:
          name: detekt
          command: |
            ./gradlew detektCheck
            mkdir -p ~/detekt/
            find . -type f -regex ".*/build/reports/detekt/.*html" -exec cp {} ~/detekt/ \;
      - store_artifacts:
          path: ~/detekt

  deploy_to_play:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - *save_gradle_cache
      - *attach_workspace
      # TODO use gradle-play-publisher once custom archivesBaseName is supported for app bundles, and publishing existing apk without building is supported.

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - unit_tests
      - static_analysis
      - deploy_to_play:
          <<: *master_only
          requires:
            - build
            - unit_tests
            - static_analysis
